#ifndef __RESTGOOSE_VERSION__
#define __RESTGOOSE_VERSION__
// These variables are autogenerated and compiled
// into the library by the version.cmake script

namespace pml
{
	namespace restgoose
	{
	    extern const char* GIT_TAG;
   	    extern const char* GIT_REV;
            extern const char* GIT_BRANCH;
	    extern const char* GIT_DATE;
	}
}
#endif
